// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Home struct {
	ID        pgtype.UUID
	UserID    int32
	Name      string
	Address   string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type Identity struct {
	ID           int32
	UserID       int32
	Username     string
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
}

type PowerConsumption struct {
	ID                          pgtype.UUID
	HomeID                      pgtype.UUID
	Power                       pgtype.Float8
	MinPower                    pgtype.Float8
	MaxPower                    pgtype.Float8
	AvgPower                    pgtype.Float8
	LastMeterConsumption        pgtype.Float8
	LastMeterProduction         pgtype.Float8
	AccumulatedConsumptionToday pgtype.Float8
	AccumulatedProductionToday  pgtype.Float8
	AccumulatedConsumptionHour  pgtype.Float8
	AccumulatedProductionHour   pgtype.Float8
	CurrentPriceFromProvider    pgtype.Float8
	AccumulatedCostToday        pgtype.Float8
	Ts                          pgtype.Timestamptz
}

type Role struct {
	ID        int32
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type User struct {
	ID        int32
	Firstname string
	Lastname  string
	Phone     pgtype.Text
	Company   pgtype.Text
	Address   pgtype.Text
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type UserRole struct {
	ID        int32
	UserID    int32
	RoleID    int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}
